name: ${project.name}
main: net.daboross.bukkitdev.rankdisplay.RankDisplayPlugin
version: ${project.version}
author: Dabo Ross
description: ${project.description}
depend: [Vault]
commands:
   rank:
     description: Views your rank or the rank of another player
     usage: /<command> [username]
